version: '2'

volumes:
 mongodb_data:

networks:
  core_network:
    #enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.26.0/24
          gateway: 192.168.26.1
        # - subnet: 200 networks:1:1001:26::/64
        #   gateway: 2001:1001:26::1

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      core_network:
        ipv4_address: 192.168.26.5

  webui:
    build: ./
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb/nextepc
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    entrypoint:
      - "npm"
      - "run"
      - "start"
      - "--prefix"
      - "/nextepc/webui" 
    networks:
      core_network:
        ipv4_address: 192.168.26.6

  hss:
    build: ./
    depends_on:
      - mongodb
    container_name: hss
    hostname: hss
    entrypoint:
      - "/bin/sh"
      - "/etc/nextepc/run_hss.sh"
    volumes:
      - "./config:/etc/nextepc"
    networks:
      core_network:
        ipv4_address: 192.168.26.10

  mme:
     build: ./
     depends_on:
       - hss
     container_name: mme
     hostname: mme
     entrypoint:
      - "/bin/sh"
      - "/etc/nextepc/run_mme.sh"
     volumes:
      - "./config:/etc/nextepc"
     networks:
       core_network:
         ipv4_address: 192.168.26.20

  sgw:
     build: ./
     container_name: sgw
     hostname: sgw
     entrypoint:
      - "/bin/sh"
      - "/etc/nextepc/run_sgw.sh"
     volumes:
      - "./config:/etc/nextepc"
     networks:
       core_network:
         ipv4_address: 192.168.26.30

  pgw:
     build: ./
     container_name: pgw
     hostname: pgw
     entrypoint:
      - "/bin/sh"
      - "/etc/nextepc/run_pgw.sh"
     volumes:
      - "./config:/etc/nextepc"
     cap_add:
       -  NET_ADMIN
     devices:
       -  /dev/net/tun
     networks:
       core_network:
         ipv4_address: 192.168.26.40

  pcrf:
    build: ./
    depends_on:
       - mongodb
       - hss
    container_name: pcrf
    hostname: pcrf
    entrypoint:
      - "/bin/sh"
      - "/etc/nextepc/run_pcrf.sh"
    volumes:
      - "./config:/etc/nextepc"
    networks:
       core_network:
         ipv4_address: 192.168.26.50

  enb:
    build: ./dummyran
    container_name: enb
    depends_on:
      - mme
    ipc: shareable
    cap_add:
      - SYS_NICE
    networks:
      core_network:
         ipv4_address: 192.168.26.60
    command:
      - srsenb
      - /config/enb.conf.fauxrf
      - --enb.name=dummyENB01
      - --enb.mcc=001
      - --enb.mnc=01
      - --enb.enb_id=18AF1
      - --enb.tac=0x0001
      - --enb.cell_id=01
      - --enb.mme_addr=192.168.26.20
      - --enb.gtp_bind_addr=192.168.26.60
      - --enb.s1c_bind_addr=192.168.26.60
      - --enb_files.rr_config=/config/rr.conf
      - --enb_files.sib_config=/config/sib.conf
      - --enb_files.drb_config=/config/drb.conf

  ue:
    container_name: ue
    build: ./dummyran
    ipc: "container:enb"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    network_mode: "none"
    depends_on:
      - enb
    command:
      - srsue
      - /config/ue.conf.fauxrf
      - --usim.imsi=001010000000001
      - --usim.k=c8eba87c1074edd06885cb0486718341
      - --usim.algo=milenage
      - --usim.opc=17b6c0157895bcaa1efc1cef55033f5f
      - --nas.apn=internet

