version: '2'

volumes:
 mongodb_data:

networks:
  core_network:
    #enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.26.0/24
          gateway: 192.168.26.1
        # - subnet: 200 networks:1:1001:26::/64
        #   gateway: 2001:1001:26::1

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      core_network:
        ipv4_address: 192.168.26.5

  webui:
    build: ./
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb/nextepc
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    volumes:
        - "./config-allinone:/etc/nextepc"
    entrypoint:
      - "/bin/sh"
      - "/etc/nextepc/run_webui.sh"
    networks:
      core_network:
        ipv4_address: 192.168.26.6


  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    volumes:
      - "./db/run_db.sh:/tmp/run.sh"
      - "./db/imsi1.json:/tmp/imsi1.json"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      core_network:
        ipv4_address: 192.168.26.19


  epc:
    build: ./
    depends_on:
      - mongodb
    container_name: epc
    hostname: epc
    entrypoint:
        - "/bin/sh"
        - "/etc/nextepc/run_epc.sh"
    volumes:
        - "./config-allinone:/etc/nextepc"
    cap_add:
       -  NET_ADMIN
    devices:
       - /dev/net/tun
    networks:
      core_network:
        ipv4_address: 192.168.26.20


  enb:
    build: ./virtual-UE-eNB
    container_name: enb
    depends_on:
      - epc
    ipc: shareable
    cap_add:
      - SYS_NICE
    networks:
      core_network:
         ipv4_address: 192.168.26.60
    command:
      - srsenb
      - /config/enb.conf.fauxrf
      - --enb.name=dummyENB01
      - --enb.mcc=001
      - --enb.mnc=01
      - --enb.enb_id=18AF1
      - --enb.tac=0x0001
      - --enb.cell_id=01
      - --enb.mme_addr=192.168.26.20
      - --enb.gtp_bind_addr=192.168.26.60
      - --enb.s1c_bind_addr=192.168.26.60
      - --enb_files.rr_config=/config/rr.conf
      - --enb_files.sib_config=/config/sib.conf
      - --enb_files.drb_config=/config/drb.conf

  ue:
    container_name: ue
    build: ./virtual-UE-eNB
    ipc: "container:enb"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    network_mode: "none"
    depends_on:
      - enb
    command:
      - srsue
      - /config/ue.conf.fauxrf
      - --usim.imsi=001010000000001
      - --usim.k=c8eba87c1074edd06885cb0486718341
      - --usim.algo=milenage
      - --usim.opc=17b6c0157895bcaa1efc1cef55033f5f
      - --nas.apn=internet

