version: '2'

networks:
  core_network:
    #enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.26.0/24
          gateway: 192.168.26.1
        # - subnet: 200 networks:1:1001:26::/64
        #   gateway: 2001:1001:26::1

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ./mongodb_data:/data/db
    hostname: mongodb
    networks:
      core_network:
        ipv4_address: 192.168.26.5

  webui:
    build: ./
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb/nextepc
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    entrypoint:
      - "npm"
      - "run"
      - "start"
      - "--prefix"
      - "/nextepc/webui" 
    networks:
      core_network:
        ipv4_address: 192.168.26.6

  hss:
    build: ./
    depends_on:
      - mongodb
    container_name: hss
    hostname: hss
    entrypoint:
      - "/bin/nextepc-hssd"
      - "-f"
      - "/etc/nextepc/hss.conf"
    volumes:
      - "./config:/etc/nextepc"
    networks:
      core_network:
        ipv4_address: 192.168.26.10

  # mme:
  #   build: ./
  #   depends_on:
  #     - mongodb
  #   container_name: mme
  #   hostname: mme
  #   entrypoint:
  #     - "/nextepc/nextepc-mmed"
  #     - "-f /config/mme.conf"
  #   volumes:
  #     - ./config:/config
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.26.20

  # sgw:
  #   build: ./
  #   depends_on:
  #     - mongodb
  #   container_name: sgw
  #   hostname: sgw
  #   entrypoint:
  #     - "/nextepc/nextepc-sgwd"
  #     - "-f /config/sgw.conf"
  #   volumes:
  #     - ./config:/config
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.26.30

  # pgw:
  #   build: ./
  #   depends_on:
  #     - mongodb
  #   container_name: pgw
  #   hostname: pgw
  #   entrypoint:
  #     - "/bin/sh"
  #     - "/config/run.sh"
  #   cap_add:
  #     -  NET_ADMIN
  #   devices:
  #     -  /dev/net/tun
  #   volumes:
  #     - ./config:/config
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.26.40

  # pcrf:
  #    build: ./
  #   depends_on:
  #     - mongodb
  #   container_name: pcrf
  #   hostname: pcrf
  #   entrypoint:
  #     - "/nextepc/nextepc-pcrfd"
  #     - "-f /config/pcrf.conf"
  #   volumes:
  #     - ./config:/config
  #   networks:
  #     core_network:
  #       ipv4_address: 192.168.26.50


